
CREATE DATABASE IF NOT EXISTS TASKS;

USE TASKS;

CREATE TABLE tasks (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(45) NOT NULL,
    local VARCHAR(45) NOT NULL,
    data VARCHAR(45) NOT NULL
);